version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devera
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'