/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package singleton;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import com.google.common.util.concurrent.Futures;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // var future01 = ThreadLocal.withInitial(() -> {
        //     return Singleton.getInstance();
        // });
        // var future02 = ThreadLocal.withInitial(() -> {
        //     return Singleton.getInstance();
        // });

        var fu01 = CompletableFuture.runAsync(() -> {
            System.out.println(Singleton.getInstance().hashCode());
        });
        var fu02 = CompletableFuture.runAsync(() -> {
            System.out.println(Singleton.getInstance().hashCode());
        });
        var fu03 = CompletableFuture.runAsync(() -> {
            System.out.println(Singleton.getInstance().hashCode());
        });

        CompletableFuture.allOf(fu01, fu02, fu03).join();

    }
}
